export const config = {
    'username': 'classdb',
    'password': '159357159',
    'database': 'postgres',
    'host': 'classdb.caucrxsqr8sj.us-east-1.rds.amazonaws.com',
    'dialect': 'postgres',
    'aws_media_bucket': process.env.AWS_BUCKET,
    'url': process.env.URL,
    // 'username': process.env.POSTGRES_USERNAME,
    // 'password': process.env.POSTGRES_PASSWORD,
    // 'database': process.env.POSTGRES_DB,
    // 'host': process.env.POSTGRES_HOST,
    // 'dialect': 'postgres',
    // 'aws_region': process.env.AWS_REGION,
    // 'aws_profile': process.env.AWS_PROFILE,
    // 'aws_media_bucket': process.env.AWS_BUCKET,
    // 'url': process.env.URL,
    'jwt': {
        'secret': process.env.JWT_SECRET,
    },
};
